# Generated by Django 4.1.5 on 2023-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_alter_pais_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=30)),
                ('imagen', models.URLField()),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
    ]
