# Generated by Django 4.1.5 on 2023-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0004_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
    ]
